name: cd

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
          - name: Check out code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
                go-version: '>=1.23.0'
            
          - name: Build app
            run:  ./scripts/buildprod.sh
          
          - name: Migrate database
            run: ./scripts/migrateup.sh

          - name: Configure gc
            run: echo "Configuring account ... "

          - name: Deploy to gc
            run: echo "gcloud builds submit"
 