name: AAAAAAAAAA!!!!!

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Print stupid stuff to the console
        run: echo "AAAAAAAA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"